# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: chess_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  pgadmin:
    container_name: chess_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - "8080:80"
      