"""empty message

Revision ID: 7832815657df
Revises: 
Create Date: 2022-12-16 21:23:39.612576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7832815657df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('scores',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('user_email', 'created_at')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_score'), ['score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_score'))
        batch_op.drop_index(batch_op.f('ix_scores_created_at'))

    op.drop_table('scores')
    op.drop_table('users')
    # ### end Alembic commands ###
